feat: добавлены контроллеры для добавления фильмов и пользователей
DiNosauur/java-filmorate pull request #2
Opened 2022-06-18 15:26 UTC by DiNosauur

2022-06-19 12:59 UTC, kukolev requested changes

2022-06-19 12:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Нарушение кодстайла: Лишние отступы слева перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-06-19 12:59 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Нарушение кодстайла: Лишние отступы слева перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-06-19 12:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(film.getName() == null || film.getName().isBlank()) {
Эти проверки повторяют код предыдущего метода. Лучше вынести все проверки в отдельный приватный методы, чтобы не дублировать код.

2022-06-19 12:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final int MAX_DESCRIPTION_LEN = 200;
Судя по всему здесь и ниже должны быть константы. Их нужно сделать публичными и добавить static.

2022-06-19 12:59 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController fc;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-06-19 12:59 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    UserController uc;
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-06-19 15:41 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
исправлено.

2022-06-19 15:41 UTC, DiNosauur commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
исправлено.

2022-06-19 15:41 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if(film.getName() == null || film.getName().isBlank()) {
Исправлено.

2022-06-19 15:42 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final int MAX_DESCRIPTION_LEN = 200;
Исправлено.

2022-06-19 15:42 UTC, DiNosauur commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    FilmController fc;
Исправлено.

2022-06-19 15:42 UTC, DiNosauur commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    UserController uc;
Исправлено.

2022-06-20 07:36 UTC, kukolev requested changes

2022-06-20 07:36 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void filmValidate(Film film) {
Нарушение кодстайла: Название метода лучше начинать с глагола, так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-06-20 07:36 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void userValidate(User user) {
Нарушение кодстайла: Название метода лучше начинать с глагола, так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-06-20 09:45 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void filmValidate(Film film) {
Исправлено.

2022-06-20 09:45 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void userValidate(User user) {
Исправлено.

2022-06-20 19:15 UTC, merged