feat: добавьте методы, позволяющие пользователям добавлять друг друга…
DiNosauur/java-filmorate pull request #3
Opened 2022-07-10 18:32 UTC by DiNosauur

… в друзья, получать список общих друзей и лайкать фильмы

2022-07-11 07:25 UTC, kukolev requested changes

2022-07-11 07:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
Не хватает логов в сервисах. Лучше покрывать сложные кейсы логами, чтобы было проще разобраться в работе программы, если что-то пойдет не так.

2022-07-11 07:25 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
Не хватает логов в сервисах. Лучше покрывать сложные кейсы логами, чтобы было проще разобраться в работе программы, если что-то пойдет не так.

2022-07-11 08:23 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
добавлено

2022-07-11 17:09 UTC, kukolev requested changes

2022-07-11 17:09 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.debug(String.format("Сохранение фильма %s", film.getName()));
Лучше использовать возможности библиотеки для логирования, чем конкатенацию строк или String.format: `log.info("Get user by id: {}", filmId)`. Так тратится меньше ресурсов и код выглядит лучше.

Исправить нужно здесь и в остальных частях программы.

2022-07-11 19:05 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.debug(String.format("Сохранение фильма %s", film.getName()));
Исправлено.

2022-07-12 07:27 UTC, kukolev approved these changes

2022-07-12 07:42 UTC, merged