feat: добавлена БД для проекта
DiNosauur/java-filmorate pull request #4
Opened 2022-07-16 15:10 UTC by DiNosauur

2022-07-17 12:29 UTC, kukolev requested changes

2022-07-17 12:29 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    {
Нарушение кодстайла: открывающаяся скобка никогда не ставится на новой строке. Нужно поправить.

2022-07-17 12:29 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "insert into FILMS(NAME, DESCRIPTION, DURATION, RELEASEDATE, MPA_ID ) " +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 12:29 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/GenreDbStorage.java
> +    public GenreDbStorage(JdbcTemplate jdbcTemplate){
Нарушение требований кодстайла: Не хватает пробела перед «{». Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-07-17 12:29 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/MPADbStorage.java
> +    public MPADbStorage(JdbcTemplate jdbcTemplate){
Нарушение требований кодстайла: Не хватает пробела перед «{». Советую в IDEA просто нажать комбинацию клавиш Ctrl + Alt + L и код автоматически отформатируется.

2022-07-17 12:29 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "select * from users";
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-17 16:47 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "select * from users";
Поправил.

2022-07-17 16:47 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/MPADbStorage.java
> +    public MPADbStorage(JdbcTemplate jdbcTemplate){
Поправил.

2022-07-17 16:47 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/GenreDbStorage.java
> +    public GenreDbStorage(JdbcTemplate jdbcTemplate){
Поправил.

2022-07-17 16:47 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    {
Поправил.

2022-07-17 16:48 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +        try {
Поправил.

2022-07-17 17:03 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "insert into FILMS(NAME, DESCRIPTION, DURATION, RELEASEDATE, MPA_ID ) " +
Поправил.

2022-07-18 07:27 UTC, kukolev requested changes

2022-07-18 07:27 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/GenreDbStorage.java
> +        String sql = "select G.* from FILM_GENRES F, GENRES G " +
Эти запросы лучше оформить как константы, тогда строка с запросом не будет создаваться каждый раз при вызове метода.

Аналогично нужно поправить ниже.

2022-07-18 09:16 UTC, DiNosauur commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/GenreDbStorage.java
> +        String sql = "select G.* from FILM_GENRES F, GENRES G " +
Исправил.

2022-07-18 17:00 UTC, kukolev approved these changes

2022-07-18 17:56 UTC, merged